### ISSUE TITLE
Does gen_neg images important?

### ISSUE THREAD

**Issue by jinfagang** [YonghaoHe/LFD-A-Light-and-Fast-Detector#7]
How's this part contribute to the whole model performance? If we dont generate neg images, how many points will drop in terms of precision and recall?

**Comment by YonghaoHe** [comment]
@jinfagang First, I give the conclusion: neg images are very important.
In traditional data pipeline of training COCO/PASCA VOC, all images are only resized without cropping to form the batch. This means all information in the images are seen. The drawback is that the input size is always large, resulting in small batch size.
In LFD, we train from scratch, so large batch size is necessary. We have to crop subimages (performed by region samplers), which means not all information in an image is always learned. neg images are crucial for compensating this issue by greatly reducing False Positives. In general, 3-5 points will drop if you do not use neg images.

**Comment by jinfagang** [comment]
@YonghaoHe From my understanding, neg samples is simple croped those image part that don't have any objects inside it? And then just feed those image to train which contains no targets?

**Comment by YonghaoHe** [comment]
@jinfagang You are right, neg images do not have any targets inside.

**Comment by jinfagang** [comment]
https://github.com/YonghaoHe/wiki-images/blob/main/LFD-wiki/WIDERFACE_test_results/image1_result_compressed.jpg @YonghaoHe It's not about Proxy

**Comment by YonghaoHe** [comment]
@jinfagang Sorry, I have changed the visibility of the repo and everything should be fine.

**Comment by jpyjpr** [comment]
> @jinfagang Sorry, I have changed the visibility of the repo and everything should be fine.

I've reviewed the code files for generating negative samples, and I'm not sure if my understanding is correct. However, from the generated negative sample images, I noticed that when following the provided method to crop the negative samples, there are numerous bounding boxes present. For instance, in my detection task, which involves counting the number of students in a classroom from a camera, due to the close proximity and high density of student seating, the cropped negative samples contain many bounding boxes around heads. Is this situation considered normal?

<img width="667" alt="2" src="https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/assets/42987291/99880e78-f87d-4f0e-9c22-b925d472ae01">
